config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :students, only: [:new, :index, :create]

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    redirect_to root_path, notice: "#{@student.name} has been added!"
  end

  protected

  def student_params
    params.require(:student).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @students = Student.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Student Picker"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    <script type="text/javascript" src="//use.typekit.net/ayn0ftv.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  %body
    %nav#main
      -# %ul
      -#   - if logged_in?
      -#     - unless request.path == root_path
      -#       %li= link_to "< Back to Dashboard", root_path
      -#     %li= link_to "Profile", edit_user_path
      -#     %li= link_to "Sign Out", user_session_path, method: :delete
      -#   - else
      -#     %li= link_to "Sign In", new_user_session_path
      -#     %li= link_to "Sign Up", new_user_path
      -# = link_to root_path, id: "logo" do
      -#   %h2.title
      -#     = image_tag "POGO_10.090_OCA.svg", class: "logo"
      -#     GreenThumb
    %main
      - if notice.present?
        .alert-box.success{ "data-alert" => "" }
          = notice
          %a.close{ href: "#" } &times;
      - if alert.present?
        .alert-box.alert{ "data-alert" => "" }
          = alert
          %a.close{ href: "#" } &times;
      = yield
    %footer


    = javascript_include_tag "application"
    = javascript_tag '$.fx.off = true;' if Rails.env.test?

app/views/students/new.html.haml
= simple_form_for Student.new do |f|
  = f.input :name
  = f.submit "Add Student"

app/views/welcome/index.html.haml
#welcome
  %h1 Student Picker

  .student_list
    -# %ul#students= render @students

  .add_student_form
    = link_to "Add Student", new_student_path, class: "button"